server:
  port: 11001

  tomcat:
    accept-count: 100
    min-spare-threads: 10
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_way?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456