server:
  port: 11001
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_way?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none