server:
  port: 11001

  tomcat:
    accept-count: 100
    min-spare-threads: 10
spring:
  datasource:
    url: jdbc:mysql://172.30.4.213:7706/tyn_test?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 1234561
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none